# 服务端口
server:
  port: 8003
  # 服务名
spring:
  application:
    name: service-vod
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M
  #阿里云 vod
  #不同的服务器，地址不同
  redis:
    host: 192.168.220.128
aliyun:
  vod:
    file:
      keyid: LTAI5tNmALhS6ybGfC6Bzd7u
      keysecret: Fh289JV4nbuHD2GfnRqB6OBmetZEpp



